AWSTemplateFormatVersion: "2010-09-09"
Description: Template for creating EC2 Instance
# parameter for existing key pairs
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

# resources section
Resources:
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "nlb-wiki"
      Scheme: internet-facing
      SubnetMappings:
        - SubnetId: !Ref AppSubnet1
      Type: network

  # target group network load balancer
  NetworkLoadBalancerTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "nlb-target"
      Port: 80
      Protocol: TCP
      VpcId: !Ref EC2VPC
      HealthCheckEnabled: True
      HealthCheckIntervalSeconds: 10
      HealthCheckPort: 80
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      TargetType: instance
      Targets:
        - Id: !Ref EC2Instance
          Port: 80

  # network load balancer
  NetworkLoadBalancerListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NetworkLoadBalancerTargetGroup
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 80
      Protocol: TCP

  # ec2 instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-2a
      ImageId: ami-00d1237fa493f4d9a
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      SubnetId: !Ref AppSubnet1
      KeyName: !Ref KeyName
      UserData:
        "Fn::Base64": |
            #!/bin/bash
            
            sudo apt-get update
            apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
            apt-get update
            apt-get install -y docker-ce
            usermod -aG docker ubuntu
            apt-get update
  
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            apt-get update
            cd /home/ubuntu/
            mkdir -p wiki
            cd wiki
            
            cat << EOF > docker-compose.yml
              version: '3'
              services:
                mediawiki:
                  image: mediawiki
                  restart: always
                  ports:
                    - 80:80
                  environment: 
                      DB_HOST: db
                      DB_PORT: 3306
                      DB_DATABASE: mediawiki
                      DB_USERNAME: root
                      DB_PASSWORD: secret
                  volumes:
                    - ./images:/var/www/html/images
                  networks:
                      - mediawiki
                db:
                  image: mysql
                  restart: always
                  environment:
                      MYSQL_DATABASE: mediawiki
                      MYSQl_USER: homestead
                      MYSQL_PASSWORD: secret
                      MYSQL_ROOT_PASSWORD: secret
                      SERVICE_TAGS: dev
                      SERVICE_NAME: mysql
                  volumes:
                    - ./db:/var/lib/mysql
                  networks:
                      - mediawiki
              networks:
                mediawiki:
            EOF
            docker-compose -f /home/ubuntu/wiki/docker-compose.yml up -d
  # an elastic IP for our instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  # ec2 security group
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: EC2 Security group 
      VpcId: !Ref EC2VPC

  # inbound http
  Ec2SecurityGroupHTTPinbound:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: TCP
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  # inbound ssh
  Ec2SecurityGroupSSHinbound:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: TCP
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  # vpc
  EC2VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: "Name"
          Value: "demo-vpc"

  # route table        
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref EC2VPC
      Tags:
        - Key: "Name"
          Value: "my-route-table"

  # route
  Route:
    Type: AWS::EC2::Route
    Properties:
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref RouteTable

  # subnet association 
  SubnetRouteTableAssocitation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref AppSubnet1

  # subnet
  AppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2a
      CidrBlock: 10.0.24.0/24
      VpcId: !Ref EC2VPC
      Tags: 
      - Key: "Name"
        Value: app-subnet-1

  AppSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2a
      CidrBlock: 10.0.25.0/24
      VpcId: !Ref EC2VPC
      Tags:
      - Key: "Name"
        Value: app-subnet-2

  AppSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2a
      CidrBlock: 10.0.26.0/24
      VpcId: !Ref EC2VPC
      Tags:
      - Key: "Name"
        Value: app-subnet-3

  # internet gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: "Name"
        Value: internet-gateway-demo

  # attach vpc with internet gateway
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref EC2VPC
